### ISSUE TITLE
質問などの会話をどうするか？

### ISSUE THREAD

**Issue by shiro83** [shiro83/Andoroid_Study_Group#2]
会話ができる環境、距離であるとも限らないのでチャットなどを利用した方法が考えられる。

条件は以下である
- 会話したログが残る
- ファイルの転送、保存が容易である。
- 自分の使えるメモスペースがある（できれば）

これを使ったら良い、これが良かった、これを使ってみたいなどの意見が欲しい。
# 

今までの使用したツールと長所/短所
[ChatWork](http://www.chatwork.com/ja/)

長所 
全ての条件を満たしている、そして使い易い 
短所 
アカウントの作成が必要  

[LINE](http://line.me/ja/)
長所 
すでにアカウントを持っている可能性が高い 
短所 
ファイルの送信などが困難、はっきり言って向いてない  

[ハングアウト](https://www.google.com/tools/dlpage/hangoutplugin)  
長所 
すでにアカウントを持っている可能性が高い（GMail） 
短所 
使ったことがないので未知数

**Comment by aikookuyama** [comment]
chatworkで良さそうです！

**Comment by shiro83** [comment]
ユーザ登録が必要ですが、chatworkします。
